data = [
"¿Python mas alla de Django? Si van a los repos populares de Python en GitHub encontraran que la mayoria de los proyectos  son para ciencia de datos, big data y otros relacionados. No me di cuenta que Python es el lenguaje por elección para #Data.",
"Comics de cientificas!! \n Para descargar gratis aqui  \n http://institucional.us.es/cientificas/comic/ \n  Demosle maxima difusion!",
"BE \n A \n PEOPLE \n BUILDER \n \n > @ALAColombia",
"How wonderful it is that nobody need wait a single moment before starting to improve the world. \n > Anne Frank",
"Programo hace 20 años y todavía me pasa que si estoy varios días y no puedo resolver algo me siento tonta y mal > @nportas",
"1/5 Cursos gratuitos sobre #JAMstack: Fundamentals http://ow.ly/lnzg50yo3zV",
"2/5 Cursos gratuitos sobre #JAMstack: Create a blog http://ow.ly/O4GJ50yo3zZ",
"3/5 Cursos gratuitos sobre #JAMstack: Create an e-commerce app http://ow.ly/BkHN50yo3A0",
"4/5 Cursos gratuitos sobre #JAMstack: Pre generate static pages http://ow.ly/t4te50yo3zS",
"5/5 Cursos gratuitos sobre #JAMstack: Authentication http://ow.ly/fmZQ50yo3zU",
"The future is something you cannot control, but it is worth dreaming years ahead. > @Marianvilla",
"Soñar es la actividad estética más antigua. > Borges",
"Cada mañana tienes dos opciones: Continuar durmiendo con tus sueños o despertarte y perseguirlos. > @Marianvilla",
"I prefer Tabs https://twitter.com/WomenWhoCode/status/1229760043979038727",
"Querido desarrollador JUNIOR: Siempre di lo que piensas",
"Querido desarrollador JUNIOR: Tu conocimiento NO ES IGUAL a tu valor humano",
"Querido desarrollador JUNIOR: Eres valioso para tu empresa",
"Querido desarrollador JUNIOR: No tienes que saber / memorizar todo",
"Querido desarrollador JUNIOR: Siempre mira para progresar",
"Querido desarrollador JUNIOR: Nunca bajes la cabeza",
"1/5 Etapas del duelo que se aplican perfectamente al debbugear código: Negación 'El compilador está equivocado'",
"2/5 Etapas del duelo que se aplican perfectamente al debbugear código: Ira '¿Por qué demonios no está funcionando?'",
"3/5 Etapas del duelo que se aplican perfectamente al debbugear código: Negociación 'Si uso suficientes print, lo resolveré'",
"4/5 Etapas del duelo que se aplican perfectamente al debbugear código: Depresión 'Nunca arreglaré este error'",
"5/5 Etapas del duelo que se aplican perfectamente al debbugear código: Aceptación 'Es una característica'",
"Amo el código. No amo la industria ni el 'negociazo'. > @ltciro",
"Querido científico de datos: Por fis aprende del negocio. > @marisbotero",
"Querido científico de datos: Los datos nunca estarán limpios. > @marisbotero",
"Querido científico de datos: Hay que tragar aguita, eso es aprender que los datos no están disponibles, que tienen inconsistencias y que los modelos no siempre funcionan a la primera. > @marisbotero",
"Aprender significa divertirte mientras fallas! > @luucamay_",
"Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. > @TatianaTMac",
"1/7 Cosas de desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: Escribí `</br>` en lugar de `<br/>` durante varios años ...",
"2/7 Cosas de desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: Utilicé en #Python print para los logs",
"3/7 Cosas fde desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: Depuré JavaScript con nada más que alert () durante años. Cuando descubrí console.log comencé a reírme de mí mismo. ¡Vengo de ser principalmente del lado del servidor donde utilicé registros y un depurador todo el tiempo!",
"4/7 Cosas de desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: La posición de mis manos en el teclado del portátil estaba y sigue estando mal. Aunque me puse muy rápido escribiendo",
"5/7 Cosas de desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: Pensé que los elementos `position: absolute` tienen que ir SIEMPRE dentro de los elementos position: relative. Aparentemente puede ser cualquier otro valor de posición excepto estático.",
"6/7 Cosas de desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: Saltar al código sin hacer un plan primero.",
"7/7 Cosas de desarrollo 'incorrectas' que hiciste durante mucho tiempo sin darte cuenta: Escribió variables globales de JavaScript EN TODAS PARTES",

"1/17 Recursos para aprender a programar: Lo recomiendo mucho! Al no ser en video, puede llegar a ser pesado PERO se explican todos los conceptos y tambien se dan ejercicios :)  -PHP, MYSQL, JAVASCRIPT ETC  http://tutorialesprogramacionya.com",
"2/17 Recursos para aprender a programar: Aca tambien tenemos una pagina con videos para aprender por ejemplo JAVA - https://ecodeup.com",
"3/17 Recursos para aprender a programar: Como ya recomende una vez Fazt da pequenos cursos con explicaciones muy buenas! https://faztweb.com",
"4/17 Recursos para aprender a programar: También es importante aclarar que plataformas como Platzi o Udemy ofrecen algunos cursos gratis (eso si, es super importante chequear que nos da el curso, tal vez se hizo hace 5 anos y actualmente no nos sirve) Dejo el link https://platzi.com/cursos/programacion-basica/",
"5/17 Recursos para aprender a programar: Voy agregar a https://codigofacilito.com que también ofrece algunos cursos gratuitos.",
"6/17 Recursos para aprender a programar: Tenemos también https://es.khanacademy.org/computing/computer-programming (Introducción a la programación, conceptos básicos y JS avanzado!)",
"7/17 Recursos para aprender a programar: Entre mi busqueda encontre esta pagina para que los mas chicxs aprendan a programar :) https://studio.code.org/courses",
"8/17 Recursos para aprender a programar: También para que aprendan jugando esta https://codecombat.com",
"9/17 Recursos para aprender a programar: Tenemos a https://youtube.com/c/ProgramacionDesdeCero @Programacion_0. Con videos para aprender Phyton, C++",
"10/17 Recursos para aprender a programar: Muchxs recomendaron https://mumuki.io/central",
"11/17 Recursos para aprender a programar: Esta tambien Pildoras Informáticas - https://youtube.com/user/pildorasinformaticas. Cursos muy completos y bien explicados. Actualmente estoy haciendo uno de MySQL y es muy bueno!!",
"12/17 Recursos para aprender a programar: Tambien me recomendaron La Geekipedia De Ernesto - https://youtube.com/user/neto376 - Cursos de Phyton, Java, Android y mucho mas!",
"13/17 Recursos para aprender a programar: También tenemos https://ed.team/cursos-gratis - Cursos gratis de programación, ya sea HTML, CSS, JAVASCRIPT, lo recomiendo!!!!",
"14/17 Recursos para aprender a programar: En EscuelaDevRock se da un curso gratis para dar tus primeros pasos en programación - https://escueladevrock.com/cursos/supervivencia",
"15/17 Recursos para aprender a programar: Permiso para colar el humilde aporte de Programación Desde Cero: http://youtube.com/c/ProgramacionDesdeCero (hecho con mucha pasión y vocación)  :)",
"16/17 Recursos para aprender a programar: Agrego: https://mumuki.io/central es super interactivo y divertido para aprender a programar y cuenta con muchos ejercicios! Incluso tiene un modo para niños/as",
"17/17 Recursos para aprender a programar: En @freeCodeCampBA también tienen hay recursos gratuitos",
"https://t.me/nucleognulinux"
]
