data = [
"¿Python mas alla de Django? Si van a los repos populares de Python en GitHub encontraran que la mayoria de los proyectos  son para ciencia de datos, big data y otros relacionados. No me di cuenta que Python es el lenguaje por elección para #Data.",
"Comics de cientificas!! \n Para descargar gratis aqui  \n http://institucional.us.es/cientificas/comic/ \n  Demosle maxima difusion!",
"BE \n A \n PEOPLE \n BUILDER \n \n > @ALAColombia",
"How wonderful it is that nobody need wait a single moment before starting to improve the world. \n > Anne Frank",
"Programo hace 20 años y todavía me pasa que si estoy varios días y no puedo resolver algo me siento tonta y mal > @nportas",
"1/5 Cursos gratuitos sobre #JAMstack: Fundamentals http://ow.ly/lnzg50yo3zV",
"2/5 Cursos gratuitos sobre #JAMstack: Create a blog http://ow.ly/O4GJ50yo3zZ",
"3/5 Cursos gratuitos sobre #JAMstack: Create an e-commerce app http://ow.ly/BkHN50yo3A0",
"4/5 Cursos gratuitos sobre #JAMstack: Pre generate static pages http://ow.ly/t4te50yo3zS",
"5/5 Cursos gratuitos sobre #JAMstack: Authentication http://ow.ly/fmZQ50yo3zU",
"The future is something you cannot control, but it is worth dreaming years ahead. > @Marianvilla",
"Soñar es la actividad estética más antigua. > Borges",
"Cada mañana tienes dos opciones: Continuar durmiendo con tus sueños o despertarte y perseguirlos. > @Marianvilla",
"I prefer Tabs https://twitter.com/WomenWhoCode/status/1229760043979038727",
"Querido desarrollador JUNIOR: Siempre di lo que piensas",
"Querido desarrollador JUNIOR: Tu conocimiento NO ES IGUAL a tu valor humano",
"Querido desarrollador JUNIOR: Eres valioso para tu empresa",
"Querido desarrollador JUNIOR: No tienes que saber / memorizar todo",
"Querido desarrollador JUNIOR: Siempre mira para progresar",
"Querido desarrollador JUNIOR: Nunca bajes la cabeza",
"1/5 Etapas del duelo que se aplican perfectamente al debbugear código: Negación 'El compilador está equivocado'",
"2/5 Etapas del duelo que se aplican perfectamente al debbugear código: Ira '¿Por qué demonios no está funcionando?'",
"3/5 Etapas del duelo que se aplican perfectamente al debbugear código: Negociación 'Si uso suficientes print, lo resolveré'",
"4/5 Etapas del duelo que se aplican perfectamente al debbugear código: Depresión 'Nunca arreglaré este error'",
"5/5 Etapas del duelo que se aplican perfectamente al debbugear código: Aceptación 'Es una característica'",
"Amo el código. No amo la industria ni el 'negociazo'. > @ltciro",
"Querido científico de datos: Por fis aprende del negocio. > @marisbotero",
"Querido científico de datos: Los datos nunca estarán limpios. > @marisbotero",
"Querido científico de datos: Hay que tragar aguita, eso es aprender que los datos no están disponibles, que tienen inconsistencias y que los modelos no siempre funcionan a la primera. > @marisbotero",
"Aprender significa divertirte mientras fallas! > @luucamay_",
"Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. Meritocracy is a satirical concept. > @TatianaTMac"
]

# wrong development things for years
